package org.rhpj.domain.entity;

public class TableTypes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_TYPES.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_TYPES.TYPE
     *
     * @return the value of TABLE_TYPES.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_TYPES.TYPE
     *
     * @param type the value for TABLE_TYPES.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}