package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Settings;
import org.rhpj.domain.entity.SettingsExample;

public interface SettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SETTINGS
     *
     * @mbg.generated
     */
    int insert(Settings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SETTINGS
     *
     * @mbg.generated
     */
    int insertSelective(Settings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SETTINGS
     *
     * @mbg.generated
     */
    List<Settings> selectByExample(SettingsExample example);
}