package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.TablePrivileges;
import org.rhpj.domain.entity.TablePrivilegesExample;

public interface TablePrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_PRIVILEGES
     *
     * @mbg.generated
     */
    int insert(TablePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_PRIVILEGES
     *
     * @mbg.generated
     */
    int insertSelective(TablePrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_PRIVILEGES
     *
     * @mbg.generated
     */
    List<TablePrivileges> selectByExample(TablePrivilegesExample example);
}