package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Triggers;
import org.rhpj.domain.entity.TriggersExample;

public interface TriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRIGGERS
     *
     * @mbg.generated
     */
    int insert(Triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRIGGERS
     *
     * @mbg.generated
     */
    int insertSelective(Triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRIGGERS
     *
     * @mbg.generated
     */
    List<Triggers> selectByExample(TriggersExample example);
}