package org.rhpj.domain.entity;

public class Constants {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.CONSTANT_CATALOG
     *
     * @mbg.generated
     */
    private String constantCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.CONSTANT_SCHEMA
     *
     * @mbg.generated
     */
    private String constantSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.CONSTANT_NAME
     *
     * @mbg.generated
     */
    private String constantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.DATA_TYPE
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANTS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.CONSTANT_CATALOG
     *
     * @return the value of CONSTANTS.CONSTANT_CATALOG
     *
     * @mbg.generated
     */
    public String getConstantCatalog() {
        return constantCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.CONSTANT_CATALOG
     *
     * @param constantCatalog the value for CONSTANTS.CONSTANT_CATALOG
     *
     * @mbg.generated
     */
    public void setConstantCatalog(String constantCatalog) {
        this.constantCatalog = constantCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.CONSTANT_SCHEMA
     *
     * @return the value of CONSTANTS.CONSTANT_SCHEMA
     *
     * @mbg.generated
     */
    public String getConstantSchema() {
        return constantSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.CONSTANT_SCHEMA
     *
     * @param constantSchema the value for CONSTANTS.CONSTANT_SCHEMA
     *
     * @mbg.generated
     */
    public void setConstantSchema(String constantSchema) {
        this.constantSchema = constantSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.CONSTANT_NAME
     *
     * @return the value of CONSTANTS.CONSTANT_NAME
     *
     * @mbg.generated
     */
    public String getConstantName() {
        return constantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.CONSTANT_NAME
     *
     * @param constantName the value for CONSTANTS.CONSTANT_NAME
     *
     * @mbg.generated
     */
    public void setConstantName(String constantName) {
        this.constantName = constantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.DATA_TYPE
     *
     * @return the value of CONSTANTS.DATA_TYPE
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.DATA_TYPE
     *
     * @param dataType the value for CONSTANTS.DATA_TYPE
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.REMARKS
     *
     * @return the value of CONSTANTS.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.REMARKS
     *
     * @param remarks the value for CONSTANTS.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.SQL
     *
     * @return the value of CONSTANTS.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.SQL
     *
     * @param sql the value for CONSTANTS.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANTS.ID
     *
     * @return the value of CONSTANTS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANTS.ID
     *
     * @param id the value for CONSTANTS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}