package org.rhpj.domain.entity;

public class Sequences {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.SEQUENCE_CATALOG
     *
     * @mbg.generated
     */
    private String sequenceCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.SEQUENCE_SCHEMA
     *
     * @mbg.generated
     */
    private String sequenceSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    private String sequenceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.CURRENT_VALUE
     *
     * @mbg.generated
     */
    private Long currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.INCREMENT
     *
     * @mbg.generated
     */
    private Long increment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.IS_GENERATED
     *
     * @mbg.generated
     */
    private Boolean isGenerated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.CACHE
     *
     * @mbg.generated
     */
    private Long cache;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.MIN_VALUE
     *
     * @mbg.generated
     */
    private Long minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.MAX_VALUE
     *
     * @mbg.generated
     */
    private Long maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.IS_CYCLE
     *
     * @mbg.generated
     */
    private Boolean isCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.SEQUENCE_CATALOG
     *
     * @return the value of SEQUENCES.SEQUENCE_CATALOG
     *
     * @mbg.generated
     */
    public String getSequenceCatalog() {
        return sequenceCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.SEQUENCE_CATALOG
     *
     * @param sequenceCatalog the value for SEQUENCES.SEQUENCE_CATALOG
     *
     * @mbg.generated
     */
    public void setSequenceCatalog(String sequenceCatalog) {
        this.sequenceCatalog = sequenceCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.SEQUENCE_SCHEMA
     *
     * @return the value of SEQUENCES.SEQUENCE_SCHEMA
     *
     * @mbg.generated
     */
    public String getSequenceSchema() {
        return sequenceSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.SEQUENCE_SCHEMA
     *
     * @param sequenceSchema the value for SEQUENCES.SEQUENCE_SCHEMA
     *
     * @mbg.generated
     */
    public void setSequenceSchema(String sequenceSchema) {
        this.sequenceSchema = sequenceSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.SEQUENCE_NAME
     *
     * @return the value of SEQUENCES.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.SEQUENCE_NAME
     *
     * @param sequenceName the value for SEQUENCES.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.CURRENT_VALUE
     *
     * @return the value of SEQUENCES.CURRENT_VALUE
     *
     * @mbg.generated
     */
    public Long getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.CURRENT_VALUE
     *
     * @param currentValue the value for SEQUENCES.CURRENT_VALUE
     *
     * @mbg.generated
     */
    public void setCurrentValue(Long currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.INCREMENT
     *
     * @return the value of SEQUENCES.INCREMENT
     *
     * @mbg.generated
     */
    public Long getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.INCREMENT
     *
     * @param increment the value for SEQUENCES.INCREMENT
     *
     * @mbg.generated
     */
    public void setIncrement(Long increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.IS_GENERATED
     *
     * @return the value of SEQUENCES.IS_GENERATED
     *
     * @mbg.generated
     */
    public Boolean getIsGenerated() {
        return isGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.IS_GENERATED
     *
     * @param isGenerated the value for SEQUENCES.IS_GENERATED
     *
     * @mbg.generated
     */
    public void setIsGenerated(Boolean isGenerated) {
        this.isGenerated = isGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.REMARKS
     *
     * @return the value of SEQUENCES.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.REMARKS
     *
     * @param remarks the value for SEQUENCES.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.CACHE
     *
     * @return the value of SEQUENCES.CACHE
     *
     * @mbg.generated
     */
    public Long getCache() {
        return cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.CACHE
     *
     * @param cache the value for SEQUENCES.CACHE
     *
     * @mbg.generated
     */
    public void setCache(Long cache) {
        this.cache = cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.MIN_VALUE
     *
     * @return the value of SEQUENCES.MIN_VALUE
     *
     * @mbg.generated
     */
    public Long getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.MIN_VALUE
     *
     * @param minValue the value for SEQUENCES.MIN_VALUE
     *
     * @mbg.generated
     */
    public void setMinValue(Long minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.MAX_VALUE
     *
     * @return the value of SEQUENCES.MAX_VALUE
     *
     * @mbg.generated
     */
    public Long getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.MAX_VALUE
     *
     * @param maxValue the value for SEQUENCES.MAX_VALUE
     *
     * @mbg.generated
     */
    public void setMaxValue(Long maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.IS_CYCLE
     *
     * @return the value of SEQUENCES.IS_CYCLE
     *
     * @mbg.generated
     */
    public Boolean getIsCycle() {
        return isCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.IS_CYCLE
     *
     * @param isCycle the value for SEQUENCES.IS_CYCLE
     *
     * @mbg.generated
     */
    public void setIsCycle(Boolean isCycle) {
        this.isCycle = isCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.ID
     *
     * @return the value of SEQUENCES.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.ID
     *
     * @param id the value for SEQUENCES.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}