package org.rhpj.domain.entity;

public class Sessions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.SESSION_START
     *
     * @mbg.generated
     */
    private String sessionStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.STATEMENT
     *
     * @mbg.generated
     */
    private String statement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.STATEMENT_START
     *
     * @mbg.generated
     */
    private String statementStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSIONS.CONTAINS_UNCOMMITTED
     *
     * @mbg.generated
     */
    private String containsUncommitted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.ID
     *
     * @return the value of SESSIONS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.ID
     *
     * @param id the value for SESSIONS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.USER_NAME
     *
     * @return the value of SESSIONS.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.USER_NAME
     *
     * @param userName the value for SESSIONS.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.SESSION_START
     *
     * @return the value of SESSIONS.SESSION_START
     *
     * @mbg.generated
     */
    public String getSessionStart() {
        return sessionStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.SESSION_START
     *
     * @param sessionStart the value for SESSIONS.SESSION_START
     *
     * @mbg.generated
     */
    public void setSessionStart(String sessionStart) {
        this.sessionStart = sessionStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.STATEMENT
     *
     * @return the value of SESSIONS.STATEMENT
     *
     * @mbg.generated
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.STATEMENT
     *
     * @param statement the value for SESSIONS.STATEMENT
     *
     * @mbg.generated
     */
    public void setStatement(String statement) {
        this.statement = statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.STATEMENT_START
     *
     * @return the value of SESSIONS.STATEMENT_START
     *
     * @mbg.generated
     */
    public String getStatementStart() {
        return statementStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.STATEMENT_START
     *
     * @param statementStart the value for SESSIONS.STATEMENT_START
     *
     * @mbg.generated
     */
    public void setStatementStart(String statementStart) {
        this.statementStart = statementStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSIONS.CONTAINS_UNCOMMITTED
     *
     * @return the value of SESSIONS.CONTAINS_UNCOMMITTED
     *
     * @mbg.generated
     */
    public String getContainsUncommitted() {
        return containsUncommitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSIONS.CONTAINS_UNCOMMITTED
     *
     * @param containsUncommitted the value for SESSIONS.CONTAINS_UNCOMMITTED
     *
     * @mbg.generated
     */
    public void setContainsUncommitted(String containsUncommitted) {
        this.containsUncommitted = containsUncommitted;
    }
}