package org.rhpj.domain.entity;

public class EquipmentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.EQUIPMENT.EQUIPMENT_ID
     *
     * @mbg.generated
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.EQUIPMENT.ROOM_ID
     *
     * @mbg.generated
     */
    private String roomId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.EQUIPMENT.EQUIPMENT_ID
     *
     * @return the value of TEST.EQUIPMENT.EQUIPMENT_ID
     *
     * @mbg.generated
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.EQUIPMENT.EQUIPMENT_ID
     *
     * @param equipmentId the value for TEST.EQUIPMENT.EQUIPMENT_ID
     *
     * @mbg.generated
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.EQUIPMENT.ROOM_ID
     *
     * @return the value of TEST.EQUIPMENT.ROOM_ID
     *
     * @mbg.generated
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.EQUIPMENT.ROOM_ID
     *
     * @param roomId the value for TEST.EQUIPMENT.ROOM_ID
     *
     * @mbg.generated
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }
}