package org.rhpj.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class ColumnsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public ColumnsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableCatalogIsNull() {
            addCriterion("TABLE_CATALOG is null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIsNotNull() {
            addCriterion("TABLE_CATALOG is not null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogEqualTo(String value) {
            addCriterion("TABLE_CATALOG =", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotEqualTo(String value) {
            addCriterion("TABLE_CATALOG <>", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThan(String value) {
            addCriterion("TABLE_CATALOG >", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG >=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThan(String value) {
            addCriterion("TABLE_CATALOG <", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG <=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLike(String value) {
            addCriterion("TABLE_CATALOG like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotLike(String value) {
            addCriterion("TABLE_CATALOG not like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIn(List<String> values) {
            addCriterion("TABLE_CATALOG in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotIn(List<String> values) {
            addCriterion("TABLE_CATALOG not in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG not between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNull() {
            addCriterion("TABLE_SCHEMA is null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNotNull() {
            addCriterion("TABLE_SCHEMA is not null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaEqualTo(String value) {
            addCriterion("TABLE_SCHEMA =", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <>", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThan(String value) {
            addCriterion("TABLE_SCHEMA >", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA >=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThan(String value) {
            addCriterion("TABLE_SCHEMA <", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLike(String value) {
            addCriterion("TABLE_SCHEMA like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotLike(String value) {
            addCriterion("TABLE_SCHEMA not like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIn(List<String> values) {
            addCriterion("TABLE_SCHEMA in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotIn(List<String> values) {
            addCriterion("TABLE_SCHEMA not in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA not between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("COLUMN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("COLUMN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(String value) {
            addCriterion("COLUMN_NAME =", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(String value) {
            addCriterion("COLUMN_NAME <>", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(String value) {
            addCriterion("COLUMN_NAME >", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME >=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(String value) {
            addCriterion("COLUMN_NAME <", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME <=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLike(String value) {
            addCriterion("COLUMN_NAME like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotLike(String value) {
            addCriterion("COLUMN_NAME not like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<String> values) {
            addCriterion("COLUMN_NAME in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<String> values) {
            addCriterion("COLUMN_NAME not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME not between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIsNull() {
            addCriterion("ORDINAL_POSITION is null");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIsNotNull() {
            addCriterion("ORDINAL_POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionEqualTo(Integer value) {
            addCriterion("ORDINAL_POSITION =", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotEqualTo(Integer value) {
            addCriterion("ORDINAL_POSITION <>", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionGreaterThan(Integer value) {
            addCriterion("ORDINAL_POSITION >", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDINAL_POSITION >=", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionLessThan(Integer value) {
            addCriterion("ORDINAL_POSITION <", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionLessThanOrEqualTo(Integer value) {
            addCriterion("ORDINAL_POSITION <=", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIn(List<Integer> values) {
            addCriterion("ORDINAL_POSITION in", values, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotIn(List<Integer> values) {
            addCriterion("ORDINAL_POSITION not in", values, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionBetween(Integer value1, Integer value2) {
            addCriterion("ORDINAL_POSITION between", value1, value2, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDINAL_POSITION not between", value1, value2, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultIsNull() {
            addCriterion("COLUMN_DEFAULT is null");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultIsNotNull() {
            addCriterion("COLUMN_DEFAULT is not null");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultEqualTo(String value) {
            addCriterion("COLUMN_DEFAULT =", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultNotEqualTo(String value) {
            addCriterion("COLUMN_DEFAULT <>", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultGreaterThan(String value) {
            addCriterion("COLUMN_DEFAULT >", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_DEFAULT >=", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultLessThan(String value) {
            addCriterion("COLUMN_DEFAULT <", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_DEFAULT <=", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultLike(String value) {
            addCriterion("COLUMN_DEFAULT like", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultNotLike(String value) {
            addCriterion("COLUMN_DEFAULT not like", value, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultIn(List<String> values) {
            addCriterion("COLUMN_DEFAULT in", values, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultNotIn(List<String> values) {
            addCriterion("COLUMN_DEFAULT not in", values, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultBetween(String value1, String value2) {
            addCriterion("COLUMN_DEFAULT between", value1, value2, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andColumnDefaultNotBetween(String value1, String value2) {
            addCriterion("COLUMN_DEFAULT not between", value1, value2, "columnDefault");
            return (Criteria) this;
        }

        public Criteria andIsNullableIsNull() {
            addCriterion("IS_NULLABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsNullableIsNotNull() {
            addCriterion("IS_NULLABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsNullableEqualTo(String value) {
            addCriterion("IS_NULLABLE =", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableNotEqualTo(String value) {
            addCriterion("IS_NULLABLE <>", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableGreaterThan(String value) {
            addCriterion("IS_NULLABLE >", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_NULLABLE >=", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableLessThan(String value) {
            addCriterion("IS_NULLABLE <", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableLessThanOrEqualTo(String value) {
            addCriterion("IS_NULLABLE <=", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableLike(String value) {
            addCriterion("IS_NULLABLE like", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableNotLike(String value) {
            addCriterion("IS_NULLABLE not like", value, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableIn(List<String> values) {
            addCriterion("IS_NULLABLE in", values, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableNotIn(List<String> values) {
            addCriterion("IS_NULLABLE not in", values, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableBetween(String value1, String value2) {
            addCriterion("IS_NULLABLE between", value1, value2, "isNullable");
            return (Criteria) this;
        }

        public Criteria andIsNullableNotBetween(String value1, String value2) {
            addCriterion("IS_NULLABLE not between", value1, value2, "isNullable");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Integer value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Integer value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Integer value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Integer value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Integer value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Integer> values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Integer> values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Integer value1, Integer value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthIsNull() {
            addCriterion("CHARACTER_MAXIMUM_LENGTH is null");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthIsNotNull() {
            addCriterion("CHARACTER_MAXIMUM_LENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthEqualTo(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH =", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthNotEqualTo(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH <>", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthGreaterThan(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH >", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH >=", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthLessThan(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH <", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthLessThanOrEqualTo(Integer value) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH <=", value, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthIn(List<Integer> values) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH in", values, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthNotIn(List<Integer> values) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH not in", values, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthBetween(Integer value1, Integer value2) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH between", value1, value2, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterMaximumLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("CHARACTER_MAXIMUM_LENGTH not between", value1, value2, "characterMaximumLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthIsNull() {
            addCriterion("CHARACTER_OCTET_LENGTH is null");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthIsNotNull() {
            addCriterion("CHARACTER_OCTET_LENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthEqualTo(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH =", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthNotEqualTo(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH <>", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthGreaterThan(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH >", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH >=", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthLessThan(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH <", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthLessThanOrEqualTo(Integer value) {
            addCriterion("CHARACTER_OCTET_LENGTH <=", value, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthIn(List<Integer> values) {
            addCriterion("CHARACTER_OCTET_LENGTH in", values, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthNotIn(List<Integer> values) {
            addCriterion("CHARACTER_OCTET_LENGTH not in", values, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthBetween(Integer value1, Integer value2) {
            addCriterion("CHARACTER_OCTET_LENGTH between", value1, value2, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andCharacterOctetLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("CHARACTER_OCTET_LENGTH not between", value1, value2, "characterOctetLength");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionIsNull() {
            addCriterion("NUMERIC_PRECISION is null");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionIsNotNull() {
            addCriterion("NUMERIC_PRECISION is not null");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION =", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionNotEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION <>", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionGreaterThan(Integer value) {
            addCriterion("NUMERIC_PRECISION >", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION >=", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionLessThan(Integer value) {
            addCriterion("NUMERIC_PRECISION <", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionLessThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION <=", value, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionIn(List<Integer> values) {
            addCriterion("NUMERIC_PRECISION in", values, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionNotIn(List<Integer> values) {
            addCriterion("NUMERIC_PRECISION not in", values, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_PRECISION between", value1, value2, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_PRECISION not between", value1, value2, "numericPrecision");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixIsNull() {
            addCriterion("NUMERIC_PRECISION_RADIX is null");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixIsNotNull() {
            addCriterion("NUMERIC_PRECISION_RADIX is not null");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX =", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixNotEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX <>", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixGreaterThan(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX >", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX >=", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixLessThan(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX <", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixLessThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_PRECISION_RADIX <=", value, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixIn(List<Integer> values) {
            addCriterion("NUMERIC_PRECISION_RADIX in", values, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixNotIn(List<Integer> values) {
            addCriterion("NUMERIC_PRECISION_RADIX not in", values, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_PRECISION_RADIX between", value1, value2, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericPrecisionRadixNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_PRECISION_RADIX not between", value1, value2, "numericPrecisionRadix");
            return (Criteria) this;
        }

        public Criteria andNumericScaleIsNull() {
            addCriterion("NUMERIC_SCALE is null");
            return (Criteria) this;
        }

        public Criteria andNumericScaleIsNotNull() {
            addCriterion("NUMERIC_SCALE is not null");
            return (Criteria) this;
        }

        public Criteria andNumericScaleEqualTo(Integer value) {
            addCriterion("NUMERIC_SCALE =", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleNotEqualTo(Integer value) {
            addCriterion("NUMERIC_SCALE <>", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleGreaterThan(Integer value) {
            addCriterion("NUMERIC_SCALE >", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleGreaterThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_SCALE >=", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleLessThan(Integer value) {
            addCriterion("NUMERIC_SCALE <", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleLessThanOrEqualTo(Integer value) {
            addCriterion("NUMERIC_SCALE <=", value, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleIn(List<Integer> values) {
            addCriterion("NUMERIC_SCALE in", values, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleNotIn(List<Integer> values) {
            addCriterion("NUMERIC_SCALE not in", values, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_SCALE between", value1, value2, "numericScale");
            return (Criteria) this;
        }

        public Criteria andNumericScaleNotBetween(Integer value1, Integer value2) {
            addCriterion("NUMERIC_SCALE not between", value1, value2, "numericScale");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameIsNull() {
            addCriterion("CHARACTER_SET_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameIsNotNull() {
            addCriterion("CHARACTER_SET_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameEqualTo(String value) {
            addCriterion("CHARACTER_SET_NAME =", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameNotEqualTo(String value) {
            addCriterion("CHARACTER_SET_NAME <>", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameGreaterThan(String value) {
            addCriterion("CHARACTER_SET_NAME >", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHARACTER_SET_NAME >=", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameLessThan(String value) {
            addCriterion("CHARACTER_SET_NAME <", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameLessThanOrEqualTo(String value) {
            addCriterion("CHARACTER_SET_NAME <=", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameLike(String value) {
            addCriterion("CHARACTER_SET_NAME like", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameNotLike(String value) {
            addCriterion("CHARACTER_SET_NAME not like", value, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameIn(List<String> values) {
            addCriterion("CHARACTER_SET_NAME in", values, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameNotIn(List<String> values) {
            addCriterion("CHARACTER_SET_NAME not in", values, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameBetween(String value1, String value2) {
            addCriterion("CHARACTER_SET_NAME between", value1, value2, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCharacterSetNameNotBetween(String value1, String value2) {
            addCriterion("CHARACTER_SET_NAME not between", value1, value2, "characterSetName");
            return (Criteria) this;
        }

        public Criteria andCollationNameIsNull() {
            addCriterion("COLLATION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCollationNameIsNotNull() {
            addCriterion("COLLATION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCollationNameEqualTo(String value) {
            addCriterion("COLLATION_NAME =", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameNotEqualTo(String value) {
            addCriterion("COLLATION_NAME <>", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameGreaterThan(String value) {
            addCriterion("COLLATION_NAME >", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLLATION_NAME >=", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameLessThan(String value) {
            addCriterion("COLLATION_NAME <", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameLessThanOrEqualTo(String value) {
            addCriterion("COLLATION_NAME <=", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameLike(String value) {
            addCriterion("COLLATION_NAME like", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameNotLike(String value) {
            addCriterion("COLLATION_NAME not like", value, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameIn(List<String> values) {
            addCriterion("COLLATION_NAME in", values, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameNotIn(List<String> values) {
            addCriterion("COLLATION_NAME not in", values, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameBetween(String value1, String value2) {
            addCriterion("COLLATION_NAME between", value1, value2, "collationName");
            return (Criteria) this;
        }

        public Criteria andCollationNameNotBetween(String value1, String value2) {
            addCriterion("COLLATION_NAME not between", value1, value2, "collationName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("TYPE_NAME =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("TYPE_NAME <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("TYPE_NAME >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("TYPE_NAME <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("TYPE_NAME like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("TYPE_NAME not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("TYPE_NAME in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("TYPE_NAME not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("TYPE_NAME between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("TYPE_NAME not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andNullableIsNull() {
            addCriterion("NULLABLE is null");
            return (Criteria) this;
        }

        public Criteria andNullableIsNotNull() {
            addCriterion("NULLABLE is not null");
            return (Criteria) this;
        }

        public Criteria andNullableEqualTo(Integer value) {
            addCriterion("NULLABLE =", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotEqualTo(Integer value) {
            addCriterion("NULLABLE <>", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableGreaterThan(Integer value) {
            addCriterion("NULLABLE >", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableGreaterThanOrEqualTo(Integer value) {
            addCriterion("NULLABLE >=", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableLessThan(Integer value) {
            addCriterion("NULLABLE <", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableLessThanOrEqualTo(Integer value) {
            addCriterion("NULLABLE <=", value, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableIn(List<Integer> values) {
            addCriterion("NULLABLE in", values, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotIn(List<Integer> values) {
            addCriterion("NULLABLE not in", values, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableBetween(Integer value1, Integer value2) {
            addCriterion("NULLABLE between", value1, value2, "nullable");
            return (Criteria) this;
        }

        public Criteria andNullableNotBetween(Integer value1, Integer value2) {
            addCriterion("NULLABLE not between", value1, value2, "nullable");
            return (Criteria) this;
        }

        public Criteria andIsComputedIsNull() {
            addCriterion("IS_COMPUTED is null");
            return (Criteria) this;
        }

        public Criteria andIsComputedIsNotNull() {
            addCriterion("IS_COMPUTED is not null");
            return (Criteria) this;
        }

        public Criteria andIsComputedEqualTo(Boolean value) {
            addCriterion("IS_COMPUTED =", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedNotEqualTo(Boolean value) {
            addCriterion("IS_COMPUTED <>", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedGreaterThan(Boolean value) {
            addCriterion("IS_COMPUTED >", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_COMPUTED >=", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedLessThan(Boolean value) {
            addCriterion("IS_COMPUTED <", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_COMPUTED <=", value, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedIn(List<Boolean> values) {
            addCriterion("IS_COMPUTED in", values, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedNotIn(List<Boolean> values) {
            addCriterion("IS_COMPUTED not in", values, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_COMPUTED between", value1, value2, "isComputed");
            return (Criteria) this;
        }

        public Criteria andIsComputedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_COMPUTED not between", value1, value2, "isComputed");
            return (Criteria) this;
        }

        public Criteria andSelectivityIsNull() {
            addCriterion("SELECTIVITY is null");
            return (Criteria) this;
        }

        public Criteria andSelectivityIsNotNull() {
            addCriterion("SELECTIVITY is not null");
            return (Criteria) this;
        }

        public Criteria andSelectivityEqualTo(Integer value) {
            addCriterion("SELECTIVITY =", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityNotEqualTo(Integer value) {
            addCriterion("SELECTIVITY <>", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityGreaterThan(Integer value) {
            addCriterion("SELECTIVITY >", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityGreaterThanOrEqualTo(Integer value) {
            addCriterion("SELECTIVITY >=", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityLessThan(Integer value) {
            addCriterion("SELECTIVITY <", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityLessThanOrEqualTo(Integer value) {
            addCriterion("SELECTIVITY <=", value, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityIn(List<Integer> values) {
            addCriterion("SELECTIVITY in", values, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityNotIn(List<Integer> values) {
            addCriterion("SELECTIVITY not in", values, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityBetween(Integer value1, Integer value2) {
            addCriterion("SELECTIVITY between", value1, value2, "selectivity");
            return (Criteria) this;
        }

        public Criteria andSelectivityNotBetween(Integer value1, Integer value2) {
            addCriterion("SELECTIVITY not between", value1, value2, "selectivity");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintIsNull() {
            addCriterion("CHECK_CONSTRAINT is null");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintIsNotNull() {
            addCriterion("CHECK_CONSTRAINT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintEqualTo(String value) {
            addCriterion("CHECK_CONSTRAINT =", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintNotEqualTo(String value) {
            addCriterion("CHECK_CONSTRAINT <>", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintGreaterThan(String value) {
            addCriterion("CHECK_CONSTRAINT >", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_CONSTRAINT >=", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintLessThan(String value) {
            addCriterion("CHECK_CONSTRAINT <", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintLessThanOrEqualTo(String value) {
            addCriterion("CHECK_CONSTRAINT <=", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintLike(String value) {
            addCriterion("CHECK_CONSTRAINT like", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintNotLike(String value) {
            addCriterion("CHECK_CONSTRAINT not like", value, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintIn(List<String> values) {
            addCriterion("CHECK_CONSTRAINT in", values, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintNotIn(List<String> values) {
            addCriterion("CHECK_CONSTRAINT not in", values, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintBetween(String value1, String value2) {
            addCriterion("CHECK_CONSTRAINT between", value1, value2, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andCheckConstraintNotBetween(String value1, String value2) {
            addCriterion("CHECK_CONSTRAINT not between", value1, value2, "checkConstraint");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIsNull() {
            addCriterion("SEQUENCE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIsNotNull() {
            addCriterion("SEQUENCE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceNameEqualTo(String value) {
            addCriterion("SEQUENCE_NAME =", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotEqualTo(String value) {
            addCriterion("SEQUENCE_NAME <>", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameGreaterThan(String value) {
            addCriterion("SEQUENCE_NAME >", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameGreaterThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_NAME >=", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLessThan(String value) {
            addCriterion("SEQUENCE_NAME <", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLessThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_NAME <=", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLike(String value) {
            addCriterion("SEQUENCE_NAME like", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotLike(String value) {
            addCriterion("SEQUENCE_NAME not like", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIn(List<String> values) {
            addCriterion("SEQUENCE_NAME in", values, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotIn(List<String> values) {
            addCriterion("SEQUENCE_NAME not in", values, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameBetween(String value1, String value2) {
            addCriterion("SEQUENCE_NAME between", value1, value2, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotBetween(String value1, String value2) {
            addCriterion("SEQUENCE_NAME not between", value1, value2, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeIsNull() {
            addCriterion("SOURCE_DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeIsNotNull() {
            addCriterion("SOURCE_DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeEqualTo(Short value) {
            addCriterion("SOURCE_DATA_TYPE =", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeNotEqualTo(Short value) {
            addCriterion("SOURCE_DATA_TYPE <>", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeGreaterThan(Short value) {
            addCriterion("SOURCE_DATA_TYPE >", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("SOURCE_DATA_TYPE >=", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeLessThan(Short value) {
            addCriterion("SOURCE_DATA_TYPE <", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeLessThanOrEqualTo(Short value) {
            addCriterion("SOURCE_DATA_TYPE <=", value, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeIn(List<Short> values) {
            addCriterion("SOURCE_DATA_TYPE in", values, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeNotIn(List<Short> values) {
            addCriterion("SOURCE_DATA_TYPE not in", values, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeBetween(Short value1, Short value2) {
            addCriterion("SOURCE_DATA_TYPE between", value1, value2, "sourceDataType");
            return (Criteria) this;
        }

        public Criteria andSourceDataTypeNotBetween(Short value1, Short value2) {
            addCriterion("SOURCE_DATA_TYPE not between", value1, value2, "sourceDataType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COLUMNS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COLUMNS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}