package org.rhpj.domain.entity;

public class InDoubt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IN_DOUBT.TRANSACTION
     *
     * @mbg.generated
     */
    private String transaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IN_DOUBT.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IN_DOUBT.TRANSACTION
     *
     * @return the value of IN_DOUBT.TRANSACTION
     *
     * @mbg.generated
     */
    public String getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IN_DOUBT.TRANSACTION
     *
     * @param transaction the value for IN_DOUBT.TRANSACTION
     *
     * @mbg.generated
     */
    public void setTransaction(String transaction) {
        this.transaction = transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IN_DOUBT.STATE
     *
     * @return the value of IN_DOUBT.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IN_DOUBT.STATE
     *
     * @param state the value for IN_DOUBT.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }
}