package org.rhpj.domain.entity;

public class Rights {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.GRANTEE
     *
     * @mbg.generated
     */
    private String grantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.GRANTEETYPE
     *
     * @mbg.generated
     */
    private String granteetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.GRANTEDROLE
     *
     * @mbg.generated
     */
    private String grantedrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.RIGHTS
     *
     * @mbg.generated
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RIGHTS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.GRANTEE
     *
     * @return the value of RIGHTS.GRANTEE
     *
     * @mbg.generated
     */
    public String getGrantee() {
        return grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.GRANTEE
     *
     * @param grantee the value for RIGHTS.GRANTEE
     *
     * @mbg.generated
     */
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.GRANTEETYPE
     *
     * @return the value of RIGHTS.GRANTEETYPE
     *
     * @mbg.generated
     */
    public String getGranteetype() {
        return granteetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.GRANTEETYPE
     *
     * @param granteetype the value for RIGHTS.GRANTEETYPE
     *
     * @mbg.generated
     */
    public void setGranteetype(String granteetype) {
        this.granteetype = granteetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.GRANTEDROLE
     *
     * @return the value of RIGHTS.GRANTEDROLE
     *
     * @mbg.generated
     */
    public String getGrantedrole() {
        return grantedrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.GRANTEDROLE
     *
     * @param grantedrole the value for RIGHTS.GRANTEDROLE
     *
     * @mbg.generated
     */
    public void setGrantedrole(String grantedrole) {
        this.grantedrole = grantedrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.RIGHTS
     *
     * @return the value of RIGHTS.RIGHTS
     *
     * @mbg.generated
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.RIGHTS
     *
     * @param rights the value for RIGHTS.RIGHTS
     *
     * @mbg.generated
     */
    public void setRights(String rights) {
        this.rights = rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.TABLE_SCHEMA
     *
     * @return the value of RIGHTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.TABLE_SCHEMA
     *
     * @param tableSchema the value for RIGHTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.TABLE_NAME
     *
     * @return the value of RIGHTS.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.TABLE_NAME
     *
     * @param tableName the value for RIGHTS.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIGHTS.ID
     *
     * @return the value of RIGHTS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIGHTS.ID
     *
     * @param id the value for RIGHTS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}