package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.FunctionAliases;
import org.rhpj.domain.entity.FunctionAliasesExample;

public interface FunctionAliasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_ALIASES
     *
     * @mbg.generated
     */
    int insert(FunctionAliases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_ALIASES
     *
     * @mbg.generated
     */
    int insertSelective(FunctionAliases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_ALIASES
     *
     * @mbg.generated
     */
    List<FunctionAliases> selectByExample(FunctionAliasesExample example);
}