package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Schemata;
import org.rhpj.domain.entity.SchemataExample;

public interface SchemataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated
     */
    int insert(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated
     */
    int insertSelective(Schemata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMATA
     *
     * @mbg.generated
     */
    List<Schemata> selectByExample(SchemataExample example);
}