package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.SessionState;
import org.rhpj.domain.entity.SessionStateExample;

public interface SessionStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION_STATE
     *
     * @mbg.generated
     */
    int insert(SessionState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION_STATE
     *
     * @mbg.generated
     */
    int insertSelective(SessionState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION_STATE
     *
     * @mbg.generated
     */
    List<SessionState> selectByExample(SessionStateExample example);
}