package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.QueryStatistics;
import org.rhpj.domain.entity.QueryStatisticsExample;

public interface QueryStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUERY_STATISTICS
     *
     * @mbg.generated
     */
    int insert(QueryStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUERY_STATISTICS
     *
     * @mbg.generated
     */
    int insertSelective(QueryStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUERY_STATISTICS
     *
     * @mbg.generated
     */
    List<QueryStatistics> selectByExample(QueryStatisticsExample example);
}