package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Views;
import org.rhpj.domain.entity.ViewsExample;

public interface ViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated
     */
    int insert(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated
     */
    int insertSelective(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated
     */
    List<Views> selectByExample(ViewsExample example);
}