package org.rhpj.domain.entity;

public class Settings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SETTINGS.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SETTINGS.VALUE
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SETTINGS.NAME
     *
     * @return the value of SETTINGS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SETTINGS.NAME
     *
     * @param name the value for SETTINGS.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SETTINGS.VALUE
     *
     * @return the value of SETTINGS.VALUE
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SETTINGS.VALUE
     *
     * @param value the value for SETTINGS.VALUE
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }
}