package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Collations;
import org.rhpj.domain.entity.CollationsExample;

public interface CollationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated
     */
    int insert(Collations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated
     */
    int insertSelective(Collations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated
     */
    List<Collations> selectByExample(CollationsExample example);
}