package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Constants;
import org.rhpj.domain.entity.ConstantsExample;

public interface ConstantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTANTS
     *
     * @mbg.generated
     */
    int insert(Constants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTANTS
     *
     * @mbg.generated
     */
    int insertSelective(Constants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTANTS
     *
     * @mbg.generated
     */
    List<Constants> selectByExample(ConstantsExample example);
}