package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Constraints;
import org.rhpj.domain.entity.ConstraintsExample;

public interface ConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTRAINTS
     *
     * @mbg.generated
     */
    int insert(Constraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTRAINTS
     *
     * @mbg.generated
     */
    int insertSelective(Constraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSTRAINTS
     *
     * @mbg.generated
     */
    List<Constraints> selectByExample(ConstraintsExample example);
}