package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.InDoubt;
import org.rhpj.domain.entity.InDoubtExample;

public interface InDoubtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN_DOUBT
     *
     * @mbg.generated
     */
    int insert(InDoubt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN_DOUBT
     *
     * @mbg.generated
     */
    int insertSelective(InDoubt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN_DOUBT
     *
     * @mbg.generated
     */
    List<InDoubt> selectByExample(InDoubtExample example);
}