package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.Rights;
import org.rhpj.domain.entity.RightsExample;

public interface RightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIGHTS
     *
     * @mbg.generated
     */
    int insert(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIGHTS
     *
     * @mbg.generated
     */
    int insertSelective(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RIGHTS
     *
     * @mbg.generated
     */
    List<Rights> selectByExample(RightsExample example);
}