package org.rhpj.domain.entity;

public class Columns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_NAME
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    private Integer ordinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    private String columnDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.IS_NULLABLE
     *
     * @mbg.generated
     */
    private String isNullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.DATA_TYPE
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbg.generated
     */
    private Integer characterMaximumLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbg.generated
     */
    private Integer characterOctetLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NUMERIC_PRECISION
     *
     * @mbg.generated
     */
    private Integer numericPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NUMERIC_PRECISION_RADIX
     *
     * @mbg.generated
     */
    private Integer numericPrecisionRadix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NUMERIC_SCALE
     *
     * @mbg.generated
     */
    private Integer numericScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    private String characterSetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.COLLATION_NAME
     *
     * @mbg.generated
     */
    private String collationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.TYPE_NAME
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.NULLABLE
     *
     * @mbg.generated
     */
    private Integer nullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.IS_COMPUTED
     *
     * @mbg.generated
     */
    private Boolean isComputed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.SELECTIVITY
     *
     * @mbg.generated
     */
    private Integer selectivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    private String checkConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    private String sequenceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLUMNS.SOURCE_DATA_TYPE
     *
     * @mbg.generated
     */
    private Short sourceDataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_CATALOG
     *
     * @return the value of COLUMNS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_CATALOG
     *
     * @param tableCatalog the value for COLUMNS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_SCHEMA
     *
     * @return the value of COLUMNS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_SCHEMA
     *
     * @param tableSchema the value for COLUMNS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TABLE_NAME
     *
     * @return the value of COLUMNS.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TABLE_NAME
     *
     * @param tableName the value for COLUMNS.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_NAME
     *
     * @return the value of COLUMNS.COLUMN_NAME
     *
     * @mbg.generated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_NAME
     *
     * @param columnName the value for COLUMNS.COLUMN_NAME
     *
     * @mbg.generated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.ORDINAL_POSITION
     *
     * @return the value of COLUMNS.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    public Integer getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.ORDINAL_POSITION
     *
     * @param ordinalPosition the value for COLUMNS.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    public void setOrdinalPosition(Integer ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLUMN_DEFAULT
     *
     * @return the value of COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    public String getColumnDefault() {
        return columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLUMN_DEFAULT
     *
     * @param columnDefault the value for COLUMNS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    public void setColumnDefault(String columnDefault) {
        this.columnDefault = columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.IS_NULLABLE
     *
     * @return the value of COLUMNS.IS_NULLABLE
     *
     * @mbg.generated
     */
    public String getIsNullable() {
        return isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.IS_NULLABLE
     *
     * @param isNullable the value for COLUMNS.IS_NULLABLE
     *
     * @mbg.generated
     */
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.DATA_TYPE
     *
     * @return the value of COLUMNS.DATA_TYPE
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.DATA_TYPE
     *
     * @param dataType the value for COLUMNS.DATA_TYPE
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @return the value of COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbg.generated
     */
    public Integer getCharacterMaximumLength() {
        return characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @param characterMaximumLength the value for COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbg.generated
     */
    public void setCharacterMaximumLength(Integer characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @return the value of COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbg.generated
     */
    public Integer getCharacterOctetLength() {
        return characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @param characterOctetLength the value for COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbg.generated
     */
    public void setCharacterOctetLength(Integer characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NUMERIC_PRECISION
     *
     * @return the value of COLUMNS.NUMERIC_PRECISION
     *
     * @mbg.generated
     */
    public Integer getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NUMERIC_PRECISION
     *
     * @param numericPrecision the value for COLUMNS.NUMERIC_PRECISION
     *
     * @mbg.generated
     */
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NUMERIC_PRECISION_RADIX
     *
     * @return the value of COLUMNS.NUMERIC_PRECISION_RADIX
     *
     * @mbg.generated
     */
    public Integer getNumericPrecisionRadix() {
        return numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NUMERIC_PRECISION_RADIX
     *
     * @param numericPrecisionRadix the value for COLUMNS.NUMERIC_PRECISION_RADIX
     *
     * @mbg.generated
     */
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NUMERIC_SCALE
     *
     * @return the value of COLUMNS.NUMERIC_SCALE
     *
     * @mbg.generated
     */
    public Integer getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NUMERIC_SCALE
     *
     * @param numericScale the value for COLUMNS.NUMERIC_SCALE
     *
     * @mbg.generated
     */
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @return the value of COLUMNS.CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for COLUMNS.CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.COLLATION_NAME
     *
     * @return the value of COLUMNS.COLLATION_NAME
     *
     * @mbg.generated
     */
    public String getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.COLLATION_NAME
     *
     * @param collationName the value for COLUMNS.COLLATION_NAME
     *
     * @mbg.generated
     */
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.TYPE_NAME
     *
     * @return the value of COLUMNS.TYPE_NAME
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.TYPE_NAME
     *
     * @param typeName the value for COLUMNS.TYPE_NAME
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.NULLABLE
     *
     * @return the value of COLUMNS.NULLABLE
     *
     * @mbg.generated
     */
    public Integer getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.NULLABLE
     *
     * @param nullable the value for COLUMNS.NULLABLE
     *
     * @mbg.generated
     */
    public void setNullable(Integer nullable) {
        this.nullable = nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.IS_COMPUTED
     *
     * @return the value of COLUMNS.IS_COMPUTED
     *
     * @mbg.generated
     */
    public Boolean getIsComputed() {
        return isComputed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.IS_COMPUTED
     *
     * @param isComputed the value for COLUMNS.IS_COMPUTED
     *
     * @mbg.generated
     */
    public void setIsComputed(Boolean isComputed) {
        this.isComputed = isComputed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.SELECTIVITY
     *
     * @return the value of COLUMNS.SELECTIVITY
     *
     * @mbg.generated
     */
    public Integer getSelectivity() {
        return selectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.SELECTIVITY
     *
     * @param selectivity the value for COLUMNS.SELECTIVITY
     *
     * @mbg.generated
     */
    public void setSelectivity(Integer selectivity) {
        this.selectivity = selectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.CHECK_CONSTRAINT
     *
     * @return the value of COLUMNS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    public String getCheckConstraint() {
        return checkConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.CHECK_CONSTRAINT
     *
     * @param checkConstraint the value for COLUMNS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    public void setCheckConstraint(String checkConstraint) {
        this.checkConstraint = checkConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.SEQUENCE_NAME
     *
     * @return the value of COLUMNS.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.SEQUENCE_NAME
     *
     * @param sequenceName the value for COLUMNS.SEQUENCE_NAME
     *
     * @mbg.generated
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.REMARKS
     *
     * @return the value of COLUMNS.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.REMARKS
     *
     * @param remarks the value for COLUMNS.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLUMNS.SOURCE_DATA_TYPE
     *
     * @return the value of COLUMNS.SOURCE_DATA_TYPE
     *
     * @mbg.generated
     */
    public Short getSourceDataType() {
        return sourceDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLUMNS.SOURCE_DATA_TYPE
     *
     * @param sourceDataType the value for COLUMNS.SOURCE_DATA_TYPE
     *
     * @mbg.generated
     */
    public void setSourceDataType(Short sourceDataType) {
        this.sourceDataType = sourceDataType;
    }
}