package org.rhpj.domain.entity;

public class Constraints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    private String constraintCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    private String constraintSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    private String constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.CONSTRAINT_TYPE
     *
     * @mbg.generated
     */
    private String constraintType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.UNIQUE_INDEX_NAME
     *
     * @mbg.generated
     */
    private String uniqueIndexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.CHECK_EXPRESSION
     *
     * @mbg.generated
     */
    private String checkExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.COLUMN_LIST
     *
     * @mbg.generated
     */
    private String columnList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTRAINTS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @return the value of CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    public String getConstraintCatalog() {
        return constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @param constraintCatalog the value for CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @return the value of CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    public String getConstraintSchema() {
        return constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @param constraintSchema the value for CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.CONSTRAINT_NAME
     *
     * @return the value of CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public String getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.CONSTRAINT_NAME
     *
     * @param constraintName the value for CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.CONSTRAINT_TYPE
     *
     * @return the value of CONSTRAINTS.CONSTRAINT_TYPE
     *
     * @mbg.generated
     */
    public String getConstraintType() {
        return constraintType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.CONSTRAINT_TYPE
     *
     * @param constraintType the value for CONSTRAINTS.CONSTRAINT_TYPE
     *
     * @mbg.generated
     */
    public void setConstraintType(String constraintType) {
        this.constraintType = constraintType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.TABLE_CATALOG
     *
     * @return the value of CONSTRAINTS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.TABLE_CATALOG
     *
     * @param tableCatalog the value for CONSTRAINTS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.TABLE_SCHEMA
     *
     * @return the value of CONSTRAINTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.TABLE_SCHEMA
     *
     * @param tableSchema the value for CONSTRAINTS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.TABLE_NAME
     *
     * @return the value of CONSTRAINTS.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.TABLE_NAME
     *
     * @param tableName the value for CONSTRAINTS.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.UNIQUE_INDEX_NAME
     *
     * @return the value of CONSTRAINTS.UNIQUE_INDEX_NAME
     *
     * @mbg.generated
     */
    public String getUniqueIndexName() {
        return uniqueIndexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.UNIQUE_INDEX_NAME
     *
     * @param uniqueIndexName the value for CONSTRAINTS.UNIQUE_INDEX_NAME
     *
     * @mbg.generated
     */
    public void setUniqueIndexName(String uniqueIndexName) {
        this.uniqueIndexName = uniqueIndexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.CHECK_EXPRESSION
     *
     * @return the value of CONSTRAINTS.CHECK_EXPRESSION
     *
     * @mbg.generated
     */
    public String getCheckExpression() {
        return checkExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.CHECK_EXPRESSION
     *
     * @param checkExpression the value for CONSTRAINTS.CHECK_EXPRESSION
     *
     * @mbg.generated
     */
    public void setCheckExpression(String checkExpression) {
        this.checkExpression = checkExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.COLUMN_LIST
     *
     * @return the value of CONSTRAINTS.COLUMN_LIST
     *
     * @mbg.generated
     */
    public String getColumnList() {
        return columnList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.COLUMN_LIST
     *
     * @param columnList the value for CONSTRAINTS.COLUMN_LIST
     *
     * @mbg.generated
     */
    public void setColumnList(String columnList) {
        this.columnList = columnList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.REMARKS
     *
     * @return the value of CONSTRAINTS.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.REMARKS
     *
     * @param remarks the value for CONSTRAINTS.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.SQL
     *
     * @return the value of CONSTRAINTS.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.SQL
     *
     * @param sql the value for CONSTRAINTS.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTRAINTS.ID
     *
     * @return the value of CONSTRAINTS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTRAINTS.ID
     *
     * @param id the value for CONSTRAINTS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}