package org.rhpj.domain.entity;

public class SessionState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSION_STATE.KEY
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SESSION_STATE.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSION_STATE.KEY
     *
     * @return the value of SESSION_STATE.KEY
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSION_STATE.KEY
     *
     * @param key the value for SESSION_STATE.KEY
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SESSION_STATE.SQL
     *
     * @return the value of SESSION_STATE.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SESSION_STATE.SQL
     *
     * @param sql the value for SESSION_STATE.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }
}