package org.rhpj.domain.entity;

public class Indexes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.NON_UNIQUE
     *
     * @mbg.generated
     */
    private Boolean nonUnique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.INDEX_NAME
     *
     * @mbg.generated
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    private Short ordinalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.COLUMN_NAME
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.CARDINALITY
     *
     * @mbg.generated
     */
    private Integer cardinality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.PRIMARY_KEY
     *
     * @mbg.generated
     */
    private Boolean primaryKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.INDEX_TYPE_NAME
     *
     * @mbg.generated
     */
    private String indexTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.IS_GENERATED
     *
     * @mbg.generated
     */
    private Boolean isGenerated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.INDEX_TYPE
     *
     * @mbg.generated
     */
    private Short indexType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.ASC_OR_DESC
     *
     * @mbg.generated
     */
    private String ascOrDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.PAGES
     *
     * @mbg.generated
     */
    private Integer pages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.FILTER_CONDITION
     *
     * @mbg.generated
     */
    private String filterCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.SORT_TYPE
     *
     * @mbg.generated
     */
    private Integer sortType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    private String constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.INDEX_CLASS
     *
     * @mbg.generated
     */
    private String indexClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEXES.AFFINITY
     *
     * @mbg.generated
     */
    private Boolean affinity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.TABLE_CATALOG
     *
     * @return the value of INDEXES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.TABLE_CATALOG
     *
     * @param tableCatalog the value for INDEXES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.TABLE_SCHEMA
     *
     * @return the value of INDEXES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.TABLE_SCHEMA
     *
     * @param tableSchema the value for INDEXES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.TABLE_NAME
     *
     * @return the value of INDEXES.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.TABLE_NAME
     *
     * @param tableName the value for INDEXES.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.NON_UNIQUE
     *
     * @return the value of INDEXES.NON_UNIQUE
     *
     * @mbg.generated
     */
    public Boolean getNonUnique() {
        return nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.NON_UNIQUE
     *
     * @param nonUnique the value for INDEXES.NON_UNIQUE
     *
     * @mbg.generated
     */
    public void setNonUnique(Boolean nonUnique) {
        this.nonUnique = nonUnique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.INDEX_NAME
     *
     * @return the value of INDEXES.INDEX_NAME
     *
     * @mbg.generated
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.INDEX_NAME
     *
     * @param indexName the value for INDEXES.INDEX_NAME
     *
     * @mbg.generated
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.ORDINAL_POSITION
     *
     * @return the value of INDEXES.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    public Short getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.ORDINAL_POSITION
     *
     * @param ordinalPosition the value for INDEXES.ORDINAL_POSITION
     *
     * @mbg.generated
     */
    public void setOrdinalPosition(Short ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.COLUMN_NAME
     *
     * @return the value of INDEXES.COLUMN_NAME
     *
     * @mbg.generated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.COLUMN_NAME
     *
     * @param columnName the value for INDEXES.COLUMN_NAME
     *
     * @mbg.generated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.CARDINALITY
     *
     * @return the value of INDEXES.CARDINALITY
     *
     * @mbg.generated
     */
    public Integer getCardinality() {
        return cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.CARDINALITY
     *
     * @param cardinality the value for INDEXES.CARDINALITY
     *
     * @mbg.generated
     */
    public void setCardinality(Integer cardinality) {
        this.cardinality = cardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.PRIMARY_KEY
     *
     * @return the value of INDEXES.PRIMARY_KEY
     *
     * @mbg.generated
     */
    public Boolean getPrimaryKey() {
        return primaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.PRIMARY_KEY
     *
     * @param primaryKey the value for INDEXES.PRIMARY_KEY
     *
     * @mbg.generated
     */
    public void setPrimaryKey(Boolean primaryKey) {
        this.primaryKey = primaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.INDEX_TYPE_NAME
     *
     * @return the value of INDEXES.INDEX_TYPE_NAME
     *
     * @mbg.generated
     */
    public String getIndexTypeName() {
        return indexTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.INDEX_TYPE_NAME
     *
     * @param indexTypeName the value for INDEXES.INDEX_TYPE_NAME
     *
     * @mbg.generated
     */
    public void setIndexTypeName(String indexTypeName) {
        this.indexTypeName = indexTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.IS_GENERATED
     *
     * @return the value of INDEXES.IS_GENERATED
     *
     * @mbg.generated
     */
    public Boolean getIsGenerated() {
        return isGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.IS_GENERATED
     *
     * @param isGenerated the value for INDEXES.IS_GENERATED
     *
     * @mbg.generated
     */
    public void setIsGenerated(Boolean isGenerated) {
        this.isGenerated = isGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.INDEX_TYPE
     *
     * @return the value of INDEXES.INDEX_TYPE
     *
     * @mbg.generated
     */
    public Short getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.INDEX_TYPE
     *
     * @param indexType the value for INDEXES.INDEX_TYPE
     *
     * @mbg.generated
     */
    public void setIndexType(Short indexType) {
        this.indexType = indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.ASC_OR_DESC
     *
     * @return the value of INDEXES.ASC_OR_DESC
     *
     * @mbg.generated
     */
    public String getAscOrDesc() {
        return ascOrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.ASC_OR_DESC
     *
     * @param ascOrDesc the value for INDEXES.ASC_OR_DESC
     *
     * @mbg.generated
     */
    public void setAscOrDesc(String ascOrDesc) {
        this.ascOrDesc = ascOrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.PAGES
     *
     * @return the value of INDEXES.PAGES
     *
     * @mbg.generated
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.PAGES
     *
     * @param pages the value for INDEXES.PAGES
     *
     * @mbg.generated
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.FILTER_CONDITION
     *
     * @return the value of INDEXES.FILTER_CONDITION
     *
     * @mbg.generated
     */
    public String getFilterCondition() {
        return filterCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.FILTER_CONDITION
     *
     * @param filterCondition the value for INDEXES.FILTER_CONDITION
     *
     * @mbg.generated
     */
    public void setFilterCondition(String filterCondition) {
        this.filterCondition = filterCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.REMARKS
     *
     * @return the value of INDEXES.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.REMARKS
     *
     * @param remarks the value for INDEXES.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.SQL
     *
     * @return the value of INDEXES.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.SQL
     *
     * @param sql the value for INDEXES.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.ID
     *
     * @return the value of INDEXES.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.ID
     *
     * @param id the value for INDEXES.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.SORT_TYPE
     *
     * @return the value of INDEXES.SORT_TYPE
     *
     * @mbg.generated
     */
    public Integer getSortType() {
        return sortType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.SORT_TYPE
     *
     * @param sortType the value for INDEXES.SORT_TYPE
     *
     * @mbg.generated
     */
    public void setSortType(Integer sortType) {
        this.sortType = sortType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.CONSTRAINT_NAME
     *
     * @return the value of INDEXES.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public String getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.CONSTRAINT_NAME
     *
     * @param constraintName the value for INDEXES.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.INDEX_CLASS
     *
     * @return the value of INDEXES.INDEX_CLASS
     *
     * @mbg.generated
     */
    public String getIndexClass() {
        return indexClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.INDEX_CLASS
     *
     * @param indexClass the value for INDEXES.INDEX_CLASS
     *
     * @mbg.generated
     */
    public void setIndexClass(String indexClass) {
        this.indexClass = indexClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEXES.AFFINITY
     *
     * @return the value of INDEXES.AFFINITY
     *
     * @mbg.generated
     */
    public Boolean getAffinity() {
        return affinity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEXES.AFFINITY
     *
     * @param affinity the value for INDEXES.AFFINITY
     *
     * @mbg.generated
     */
    public void setAffinity(Boolean affinity) {
        this.affinity = affinity;
    }
}