package org.rhpj.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class IndexesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public IndexesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableCatalogIsNull() {
            addCriterion("TABLE_CATALOG is null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIsNotNull() {
            addCriterion("TABLE_CATALOG is not null");
            return (Criteria) this;
        }

        public Criteria andTableCatalogEqualTo(String value) {
            addCriterion("TABLE_CATALOG =", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotEqualTo(String value) {
            addCriterion("TABLE_CATALOG <>", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThan(String value) {
            addCriterion("TABLE_CATALOG >", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG >=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThan(String value) {
            addCriterion("TABLE_CATALOG <", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CATALOG <=", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogLike(String value) {
            addCriterion("TABLE_CATALOG like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotLike(String value) {
            addCriterion("TABLE_CATALOG not like", value, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogIn(List<String> values) {
            addCriterion("TABLE_CATALOG in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotIn(List<String> values) {
            addCriterion("TABLE_CATALOG not in", values, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableCatalogNotBetween(String value1, String value2) {
            addCriterion("TABLE_CATALOG not between", value1, value2, "tableCatalog");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNull() {
            addCriterion("TABLE_SCHEMA is null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNotNull() {
            addCriterion("TABLE_SCHEMA is not null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaEqualTo(String value) {
            addCriterion("TABLE_SCHEMA =", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <>", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThan(String value) {
            addCriterion("TABLE_SCHEMA >", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA >=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThan(String value) {
            addCriterion("TABLE_SCHEMA <", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLike(String value) {
            addCriterion("TABLE_SCHEMA like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotLike(String value) {
            addCriterion("TABLE_SCHEMA not like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIn(List<String> values) {
            addCriterion("TABLE_SCHEMA in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotIn(List<String> values) {
            addCriterion("TABLE_SCHEMA not in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA not between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andNonUniqueIsNull() {
            addCriterion("NON_UNIQUE is null");
            return (Criteria) this;
        }

        public Criteria andNonUniqueIsNotNull() {
            addCriterion("NON_UNIQUE is not null");
            return (Criteria) this;
        }

        public Criteria andNonUniqueEqualTo(Boolean value) {
            addCriterion("NON_UNIQUE =", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueNotEqualTo(Boolean value) {
            addCriterion("NON_UNIQUE <>", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueGreaterThan(Boolean value) {
            addCriterion("NON_UNIQUE >", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueGreaterThanOrEqualTo(Boolean value) {
            addCriterion("NON_UNIQUE >=", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueLessThan(Boolean value) {
            addCriterion("NON_UNIQUE <", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueLessThanOrEqualTo(Boolean value) {
            addCriterion("NON_UNIQUE <=", value, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueIn(List<Boolean> values) {
            addCriterion("NON_UNIQUE in", values, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueNotIn(List<Boolean> values) {
            addCriterion("NON_UNIQUE not in", values, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueBetween(Boolean value1, Boolean value2) {
            addCriterion("NON_UNIQUE between", value1, value2, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andNonUniqueNotBetween(Boolean value1, Boolean value2) {
            addCriterion("NON_UNIQUE not between", value1, value2, "nonUnique");
            return (Criteria) this;
        }

        public Criteria andIndexNameIsNull() {
            addCriterion("INDEX_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIndexNameIsNotNull() {
            addCriterion("INDEX_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIndexNameEqualTo(String value) {
            addCriterion("INDEX_NAME =", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotEqualTo(String value) {
            addCriterion("INDEX_NAME <>", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameGreaterThan(String value) {
            addCriterion("INDEX_NAME >", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameGreaterThanOrEqualTo(String value) {
            addCriterion("INDEX_NAME >=", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLessThan(String value) {
            addCriterion("INDEX_NAME <", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLessThanOrEqualTo(String value) {
            addCriterion("INDEX_NAME <=", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLike(String value) {
            addCriterion("INDEX_NAME like", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotLike(String value) {
            addCriterion("INDEX_NAME not like", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameIn(List<String> values) {
            addCriterion("INDEX_NAME in", values, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotIn(List<String> values) {
            addCriterion("INDEX_NAME not in", values, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameBetween(String value1, String value2) {
            addCriterion("INDEX_NAME between", value1, value2, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotBetween(String value1, String value2) {
            addCriterion("INDEX_NAME not between", value1, value2, "indexName");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIsNull() {
            addCriterion("ORDINAL_POSITION is null");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIsNotNull() {
            addCriterion("ORDINAL_POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionEqualTo(Short value) {
            addCriterion("ORDINAL_POSITION =", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotEqualTo(Short value) {
            addCriterion("ORDINAL_POSITION <>", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionGreaterThan(Short value) {
            addCriterion("ORDINAL_POSITION >", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionGreaterThanOrEqualTo(Short value) {
            addCriterion("ORDINAL_POSITION >=", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionLessThan(Short value) {
            addCriterion("ORDINAL_POSITION <", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionLessThanOrEqualTo(Short value) {
            addCriterion("ORDINAL_POSITION <=", value, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionIn(List<Short> values) {
            addCriterion("ORDINAL_POSITION in", values, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotIn(List<Short> values) {
            addCriterion("ORDINAL_POSITION not in", values, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionBetween(Short value1, Short value2) {
            addCriterion("ORDINAL_POSITION between", value1, value2, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andOrdinalPositionNotBetween(Short value1, Short value2) {
            addCriterion("ORDINAL_POSITION not between", value1, value2, "ordinalPosition");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("COLUMN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("COLUMN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(String value) {
            addCriterion("COLUMN_NAME =", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(String value) {
            addCriterion("COLUMN_NAME <>", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(String value) {
            addCriterion("COLUMN_NAME >", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME >=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(String value) {
            addCriterion("COLUMN_NAME <", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME <=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLike(String value) {
            addCriterion("COLUMN_NAME like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotLike(String value) {
            addCriterion("COLUMN_NAME not like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<String> values) {
            addCriterion("COLUMN_NAME in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<String> values) {
            addCriterion("COLUMN_NAME not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME not between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andCardinalityIsNull() {
            addCriterion("CARDINALITY is null");
            return (Criteria) this;
        }

        public Criteria andCardinalityIsNotNull() {
            addCriterion("CARDINALITY is not null");
            return (Criteria) this;
        }

        public Criteria andCardinalityEqualTo(Integer value) {
            addCriterion("CARDINALITY =", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityNotEqualTo(Integer value) {
            addCriterion("CARDINALITY <>", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityGreaterThan(Integer value) {
            addCriterion("CARDINALITY >", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityGreaterThanOrEqualTo(Integer value) {
            addCriterion("CARDINALITY >=", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityLessThan(Integer value) {
            addCriterion("CARDINALITY <", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityLessThanOrEqualTo(Integer value) {
            addCriterion("CARDINALITY <=", value, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityIn(List<Integer> values) {
            addCriterion("CARDINALITY in", values, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityNotIn(List<Integer> values) {
            addCriterion("CARDINALITY not in", values, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityBetween(Integer value1, Integer value2) {
            addCriterion("CARDINALITY between", value1, value2, "cardinality");
            return (Criteria) this;
        }

        public Criteria andCardinalityNotBetween(Integer value1, Integer value2) {
            addCriterion("CARDINALITY not between", value1, value2, "cardinality");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyIsNull() {
            addCriterion("PRIMARY_KEY is null");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyIsNotNull() {
            addCriterion("PRIMARY_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyEqualTo(Boolean value) {
            addCriterion("PRIMARY_KEY =", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyNotEqualTo(Boolean value) {
            addCriterion("PRIMARY_KEY <>", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyGreaterThan(Boolean value) {
            addCriterion("PRIMARY_KEY >", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("PRIMARY_KEY >=", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyLessThan(Boolean value) {
            addCriterion("PRIMARY_KEY <", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyLessThanOrEqualTo(Boolean value) {
            addCriterion("PRIMARY_KEY <=", value, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyIn(List<Boolean> values) {
            addCriterion("PRIMARY_KEY in", values, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyNotIn(List<Boolean> values) {
            addCriterion("PRIMARY_KEY not in", values, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyBetween(Boolean value1, Boolean value2) {
            addCriterion("PRIMARY_KEY between", value1, value2, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("PRIMARY_KEY not between", value1, value2, "primaryKey");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameIsNull() {
            addCriterion("INDEX_TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameIsNotNull() {
            addCriterion("INDEX_TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameEqualTo(String value) {
            addCriterion("INDEX_TYPE_NAME =", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameNotEqualTo(String value) {
            addCriterion("INDEX_TYPE_NAME <>", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameGreaterThan(String value) {
            addCriterion("INDEX_TYPE_NAME >", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("INDEX_TYPE_NAME >=", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameLessThan(String value) {
            addCriterion("INDEX_TYPE_NAME <", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameLessThanOrEqualTo(String value) {
            addCriterion("INDEX_TYPE_NAME <=", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameLike(String value) {
            addCriterion("INDEX_TYPE_NAME like", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameNotLike(String value) {
            addCriterion("INDEX_TYPE_NAME not like", value, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameIn(List<String> values) {
            addCriterion("INDEX_TYPE_NAME in", values, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameNotIn(List<String> values) {
            addCriterion("INDEX_TYPE_NAME not in", values, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameBetween(String value1, String value2) {
            addCriterion("INDEX_TYPE_NAME between", value1, value2, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNameNotBetween(String value1, String value2) {
            addCriterion("INDEX_TYPE_NAME not between", value1, value2, "indexTypeName");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedIsNull() {
            addCriterion("IS_GENERATED is null");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedIsNotNull() {
            addCriterion("IS_GENERATED is not null");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedEqualTo(Boolean value) {
            addCriterion("IS_GENERATED =", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedNotEqualTo(Boolean value) {
            addCriterion("IS_GENERATED <>", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedGreaterThan(Boolean value) {
            addCriterion("IS_GENERATED >", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_GENERATED >=", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedLessThan(Boolean value) {
            addCriterion("IS_GENERATED <", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_GENERATED <=", value, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedIn(List<Boolean> values) {
            addCriterion("IS_GENERATED in", values, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedNotIn(List<Boolean> values) {
            addCriterion("IS_GENERATED not in", values, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_GENERATED between", value1, value2, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIsGeneratedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_GENERATED not between", value1, value2, "isGenerated");
            return (Criteria) this;
        }

        public Criteria andIndexTypeIsNull() {
            addCriterion("INDEX_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIndexTypeIsNotNull() {
            addCriterion("INDEX_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIndexTypeEqualTo(Short value) {
            addCriterion("INDEX_TYPE =", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNotEqualTo(Short value) {
            addCriterion("INDEX_TYPE <>", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeGreaterThan(Short value) {
            addCriterion("INDEX_TYPE >", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("INDEX_TYPE >=", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeLessThan(Short value) {
            addCriterion("INDEX_TYPE <", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeLessThanOrEqualTo(Short value) {
            addCriterion("INDEX_TYPE <=", value, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeIn(List<Short> values) {
            addCriterion("INDEX_TYPE in", values, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNotIn(List<Short> values) {
            addCriterion("INDEX_TYPE not in", values, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeBetween(Short value1, Short value2) {
            addCriterion("INDEX_TYPE between", value1, value2, "indexType");
            return (Criteria) this;
        }

        public Criteria andIndexTypeNotBetween(Short value1, Short value2) {
            addCriterion("INDEX_TYPE not between", value1, value2, "indexType");
            return (Criteria) this;
        }

        public Criteria andAscOrDescIsNull() {
            addCriterion("ASC_OR_DESC is null");
            return (Criteria) this;
        }

        public Criteria andAscOrDescIsNotNull() {
            addCriterion("ASC_OR_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andAscOrDescEqualTo(String value) {
            addCriterion("ASC_OR_DESC =", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescNotEqualTo(String value) {
            addCriterion("ASC_OR_DESC <>", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescGreaterThan(String value) {
            addCriterion("ASC_OR_DESC >", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescGreaterThanOrEqualTo(String value) {
            addCriterion("ASC_OR_DESC >=", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescLessThan(String value) {
            addCriterion("ASC_OR_DESC <", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescLessThanOrEqualTo(String value) {
            addCriterion("ASC_OR_DESC <=", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescLike(String value) {
            addCriterion("ASC_OR_DESC like", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescNotLike(String value) {
            addCriterion("ASC_OR_DESC not like", value, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescIn(List<String> values) {
            addCriterion("ASC_OR_DESC in", values, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescNotIn(List<String> values) {
            addCriterion("ASC_OR_DESC not in", values, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescBetween(String value1, String value2) {
            addCriterion("ASC_OR_DESC between", value1, value2, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andAscOrDescNotBetween(String value1, String value2) {
            addCriterion("ASC_OR_DESC not between", value1, value2, "ascOrDesc");
            return (Criteria) this;
        }

        public Criteria andPagesIsNull() {
            addCriterion("PAGES is null");
            return (Criteria) this;
        }

        public Criteria andPagesIsNotNull() {
            addCriterion("PAGES is not null");
            return (Criteria) this;
        }

        public Criteria andPagesEqualTo(Integer value) {
            addCriterion("PAGES =", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesNotEqualTo(Integer value) {
            addCriterion("PAGES <>", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesGreaterThan(Integer value) {
            addCriterion("PAGES >", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAGES >=", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesLessThan(Integer value) {
            addCriterion("PAGES <", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesLessThanOrEqualTo(Integer value) {
            addCriterion("PAGES <=", value, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesIn(List<Integer> values) {
            addCriterion("PAGES in", values, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesNotIn(List<Integer> values) {
            addCriterion("PAGES not in", values, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesBetween(Integer value1, Integer value2) {
            addCriterion("PAGES between", value1, value2, "pages");
            return (Criteria) this;
        }

        public Criteria andPagesNotBetween(Integer value1, Integer value2) {
            addCriterion("PAGES not between", value1, value2, "pages");
            return (Criteria) this;
        }

        public Criteria andFilterConditionIsNull() {
            addCriterion("FILTER_CONDITION is null");
            return (Criteria) this;
        }

        public Criteria andFilterConditionIsNotNull() {
            addCriterion("FILTER_CONDITION is not null");
            return (Criteria) this;
        }

        public Criteria andFilterConditionEqualTo(String value) {
            addCriterion("FILTER_CONDITION =", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionNotEqualTo(String value) {
            addCriterion("FILTER_CONDITION <>", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionGreaterThan(String value) {
            addCriterion("FILTER_CONDITION >", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionGreaterThanOrEqualTo(String value) {
            addCriterion("FILTER_CONDITION >=", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionLessThan(String value) {
            addCriterion("FILTER_CONDITION <", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionLessThanOrEqualTo(String value) {
            addCriterion("FILTER_CONDITION <=", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionLike(String value) {
            addCriterion("FILTER_CONDITION like", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionNotLike(String value) {
            addCriterion("FILTER_CONDITION not like", value, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionIn(List<String> values) {
            addCriterion("FILTER_CONDITION in", values, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionNotIn(List<String> values) {
            addCriterion("FILTER_CONDITION not in", values, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionBetween(String value1, String value2) {
            addCriterion("FILTER_CONDITION between", value1, value2, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andFilterConditionNotBetween(String value1, String value2) {
            addCriterion("FILTER_CONDITION not between", value1, value2, "filterCondition");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andSqlIsNull() {
            addCriterion("SQL is null");
            return (Criteria) this;
        }

        public Criteria andSqlIsNotNull() {
            addCriterion("SQL is not null");
            return (Criteria) this;
        }

        public Criteria andSqlEqualTo(String value) {
            addCriterion("SQL =", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotEqualTo(String value) {
            addCriterion("SQL <>", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlGreaterThan(String value) {
            addCriterion("SQL >", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlGreaterThanOrEqualTo(String value) {
            addCriterion("SQL >=", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLessThan(String value) {
            addCriterion("SQL <", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLessThanOrEqualTo(String value) {
            addCriterion("SQL <=", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLike(String value) {
            addCriterion("SQL like", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotLike(String value) {
            addCriterion("SQL not like", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlIn(List<String> values) {
            addCriterion("SQL in", values, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotIn(List<String> values) {
            addCriterion("SQL not in", values, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlBetween(String value1, String value2) {
            addCriterion("SQL between", value1, value2, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotBetween(String value1, String value2) {
            addCriterion("SQL not between", value1, value2, "sql");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSortTypeIsNull() {
            addCriterion("SORT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSortTypeIsNotNull() {
            addCriterion("SORT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSortTypeEqualTo(Integer value) {
            addCriterion("SORT_TYPE =", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeNotEqualTo(Integer value) {
            addCriterion("SORT_TYPE <>", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeGreaterThan(Integer value) {
            addCriterion("SORT_TYPE >", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_TYPE >=", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeLessThan(Integer value) {
            addCriterion("SORT_TYPE <", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_TYPE <=", value, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeIn(List<Integer> values) {
            addCriterion("SORT_TYPE in", values, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeNotIn(List<Integer> values) {
            addCriterion("SORT_TYPE not in", values, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeBetween(Integer value1, Integer value2) {
            addCriterion("SORT_TYPE between", value1, value2, "sortType");
            return (Criteria) this;
        }

        public Criteria andSortTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_TYPE not between", value1, value2, "sortType");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIsNull() {
            addCriterion("CONSTRAINT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIsNotNull() {
            addCriterion("CONSTRAINT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintNameEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME =", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME <>", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameGreaterThan(String value) {
            addCriterion("CONSTRAINT_NAME >", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME >=", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLessThan(String value) {
            addCriterion("CONSTRAINT_NAME <", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLessThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME <=", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLike(String value) {
            addCriterion("CONSTRAINT_NAME like", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotLike(String value) {
            addCriterion("CONSTRAINT_NAME not like", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIn(List<String> values) {
            addCriterion("CONSTRAINT_NAME in", values, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotIn(List<String> values) {
            addCriterion("CONSTRAINT_NAME not in", values, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_NAME between", value1, value2, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_NAME not between", value1, value2, "constraintName");
            return (Criteria) this;
        }

        public Criteria andIndexClassIsNull() {
            addCriterion("INDEX_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andIndexClassIsNotNull() {
            addCriterion("INDEX_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andIndexClassEqualTo(String value) {
            addCriterion("INDEX_CLASS =", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassNotEqualTo(String value) {
            addCriterion("INDEX_CLASS <>", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassGreaterThan(String value) {
            addCriterion("INDEX_CLASS >", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassGreaterThanOrEqualTo(String value) {
            addCriterion("INDEX_CLASS >=", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassLessThan(String value) {
            addCriterion("INDEX_CLASS <", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassLessThanOrEqualTo(String value) {
            addCriterion("INDEX_CLASS <=", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassLike(String value) {
            addCriterion("INDEX_CLASS like", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassNotLike(String value) {
            addCriterion("INDEX_CLASS not like", value, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassIn(List<String> values) {
            addCriterion("INDEX_CLASS in", values, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassNotIn(List<String> values) {
            addCriterion("INDEX_CLASS not in", values, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassBetween(String value1, String value2) {
            addCriterion("INDEX_CLASS between", value1, value2, "indexClass");
            return (Criteria) this;
        }

        public Criteria andIndexClassNotBetween(String value1, String value2) {
            addCriterion("INDEX_CLASS not between", value1, value2, "indexClass");
            return (Criteria) this;
        }

        public Criteria andAffinityIsNull() {
            addCriterion("AFFINITY is null");
            return (Criteria) this;
        }

        public Criteria andAffinityIsNotNull() {
            addCriterion("AFFINITY is not null");
            return (Criteria) this;
        }

        public Criteria andAffinityEqualTo(Boolean value) {
            addCriterion("AFFINITY =", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityNotEqualTo(Boolean value) {
            addCriterion("AFFINITY <>", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityGreaterThan(Boolean value) {
            addCriterion("AFFINITY >", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityGreaterThanOrEqualTo(Boolean value) {
            addCriterion("AFFINITY >=", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityLessThan(Boolean value) {
            addCriterion("AFFINITY <", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityLessThanOrEqualTo(Boolean value) {
            addCriterion("AFFINITY <=", value, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityIn(List<Boolean> values) {
            addCriterion("AFFINITY in", values, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityNotIn(List<Boolean> values) {
            addCriterion("AFFINITY not in", values, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityBetween(Boolean value1, Boolean value2) {
            addCriterion("AFFINITY between", value1, value2, "affinity");
            return (Criteria) this;
        }

        public Criteria andAffinityNotBetween(Boolean value1, Boolean value2) {
            addCriterion("AFFINITY not between", value1, value2, "affinity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INDEXES
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INDEXES
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}