package org.rhpj.domain.client;

import java.util.List;
import org.rhpj.domain.entity.CrossReferences;
import org.rhpj.domain.entity.CrossReferencesExample;

public interface CrossReferencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CROSS_REFERENCES
     *
     * @mbg.generated
     */
    int insert(CrossReferences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CROSS_REFERENCES
     *
     * @mbg.generated
     */
    int insertSelective(CrossReferences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CROSS_REFERENCES
     *
     * @mbg.generated
     */
    List<CrossReferences> selectByExample(CrossReferencesExample example);
}