CREATE SCHEMA IF NOT EXISTS TEST;
SET SCHEMA TEST;

-- アカウント
--CREATE TABLE IF NOT EXISTS ACCOUNT (
--  USERNAME VARCHAR(10) NOT NULL,
--  PASSWORD VARCHAR(30) NOT NULL,
--  PRIMARY KEY(USERNAME)
--);
-- 部屋
CREATE TABLE IF NOT EXISTS ROOM (
  ROOM_ID VARCHAR(10) NOT NULL,
  ROOM_NAME VARCHAR(30) NOT NULL,
  CAPACITY INT NOT NULL,
  PRIMARY KEY(ROOM_ID)
);
-- 備品
CREATE TABLE IF NOT EXISTS EQUIPMENT (
  EQUIPMENT_ID VARCHAR(10) NOT NULL,
  ROOM_ID VARCHAR(30) NOT NULL,
  EQUIPMENT_NAME VARCHAR(30) NOT NULL,
  EQUIPMENT_COUNT INT NOT NULL,
  EQUIPMENT_REMARKS VARCHAR(100),
  PRIMARY KEY(EQUIPMENT_ID, ROOM_ID),
  FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

