package org.rhpj.domain.entity;

public class Domains {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.DOMAIN_CATALOG
     *
     * @mbg.generated
     */
    private String domainCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.DOMAIN_SCHEMA
     *
     * @mbg.generated
     */
    private String domainSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.DOMAIN_NAME
     *
     * @mbg.generated
     */
    private String domainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    private String columnDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.IS_NULLABLE
     *
     * @mbg.generated
     */
    private String isNullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.DATA_TYPE
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.PRECISION
     *
     * @mbg.generated
     */
    private Integer precision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.SCALE
     *
     * @mbg.generated
     */
    private Integer scale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.TYPE_NAME
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.SELECTIVITY
     *
     * @mbg.generated
     */
    private Integer selectivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    private String checkConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOMAINS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.DOMAIN_CATALOG
     *
     * @return the value of DOMAINS.DOMAIN_CATALOG
     *
     * @mbg.generated
     */
    public String getDomainCatalog() {
        return domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.DOMAIN_CATALOG
     *
     * @param domainCatalog the value for DOMAINS.DOMAIN_CATALOG
     *
     * @mbg.generated
     */
    public void setDomainCatalog(String domainCatalog) {
        this.domainCatalog = domainCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.DOMAIN_SCHEMA
     *
     * @return the value of DOMAINS.DOMAIN_SCHEMA
     *
     * @mbg.generated
     */
    public String getDomainSchema() {
        return domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.DOMAIN_SCHEMA
     *
     * @param domainSchema the value for DOMAINS.DOMAIN_SCHEMA
     *
     * @mbg.generated
     */
    public void setDomainSchema(String domainSchema) {
        this.domainSchema = domainSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.DOMAIN_NAME
     *
     * @return the value of DOMAINS.DOMAIN_NAME
     *
     * @mbg.generated
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.DOMAIN_NAME
     *
     * @param domainName the value for DOMAINS.DOMAIN_NAME
     *
     * @mbg.generated
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.COLUMN_DEFAULT
     *
     * @return the value of DOMAINS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    public String getColumnDefault() {
        return columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.COLUMN_DEFAULT
     *
     * @param columnDefault the value for DOMAINS.COLUMN_DEFAULT
     *
     * @mbg.generated
     */
    public void setColumnDefault(String columnDefault) {
        this.columnDefault = columnDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.IS_NULLABLE
     *
     * @return the value of DOMAINS.IS_NULLABLE
     *
     * @mbg.generated
     */
    public String getIsNullable() {
        return isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.IS_NULLABLE
     *
     * @param isNullable the value for DOMAINS.IS_NULLABLE
     *
     * @mbg.generated
     */
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.DATA_TYPE
     *
     * @return the value of DOMAINS.DATA_TYPE
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.DATA_TYPE
     *
     * @param dataType the value for DOMAINS.DATA_TYPE
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.PRECISION
     *
     * @return the value of DOMAINS.PRECISION
     *
     * @mbg.generated
     */
    public Integer getPrecision() {
        return precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.PRECISION
     *
     * @param precision the value for DOMAINS.PRECISION
     *
     * @mbg.generated
     */
    public void setPrecision(Integer precision) {
        this.precision = precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.SCALE
     *
     * @return the value of DOMAINS.SCALE
     *
     * @mbg.generated
     */
    public Integer getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.SCALE
     *
     * @param scale the value for DOMAINS.SCALE
     *
     * @mbg.generated
     */
    public void setScale(Integer scale) {
        this.scale = scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.TYPE_NAME
     *
     * @return the value of DOMAINS.TYPE_NAME
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.TYPE_NAME
     *
     * @param typeName the value for DOMAINS.TYPE_NAME
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.SELECTIVITY
     *
     * @return the value of DOMAINS.SELECTIVITY
     *
     * @mbg.generated
     */
    public Integer getSelectivity() {
        return selectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.SELECTIVITY
     *
     * @param selectivity the value for DOMAINS.SELECTIVITY
     *
     * @mbg.generated
     */
    public void setSelectivity(Integer selectivity) {
        this.selectivity = selectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.CHECK_CONSTRAINT
     *
     * @return the value of DOMAINS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    public String getCheckConstraint() {
        return checkConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.CHECK_CONSTRAINT
     *
     * @param checkConstraint the value for DOMAINS.CHECK_CONSTRAINT
     *
     * @mbg.generated
     */
    public void setCheckConstraint(String checkConstraint) {
        this.checkConstraint = checkConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.REMARKS
     *
     * @return the value of DOMAINS.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.REMARKS
     *
     * @param remarks the value for DOMAINS.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.SQL
     *
     * @return the value of DOMAINS.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.SQL
     *
     * @param sql the value for DOMAINS.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOMAINS.ID
     *
     * @return the value of DOMAINS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOMAINS.ID
     *
     * @param id the value for DOMAINS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}