package org.rhpj.domain.entity;

public class Tables {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TABLE_TYPE
     *
     * @mbg.generated
     */
    private String tableType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.STORAGE_TYPE
     *
     * @mbg.generated
     */
    private String storageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.SQL
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.LAST_MODIFICATION
     *
     * @mbg.generated
     */
    private Long lastModification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TYPE_NAME
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.TABLE_CLASS
     *
     * @mbg.generated
     */
    private String tableClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLES.ROW_COUNT_ESTIMATE
     *
     * @mbg.generated
     */
    private Long rowCountEstimate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TABLE_CATALOG
     *
     * @return the value of TABLES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TABLE_CATALOG
     *
     * @param tableCatalog the value for TABLES.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TABLE_SCHEMA
     *
     * @return the value of TABLES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TABLE_SCHEMA
     *
     * @param tableSchema the value for TABLES.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TABLE_NAME
     *
     * @return the value of TABLES.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TABLE_NAME
     *
     * @param tableName the value for TABLES.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TABLE_TYPE
     *
     * @return the value of TABLES.TABLE_TYPE
     *
     * @mbg.generated
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TABLE_TYPE
     *
     * @param tableType the value for TABLES.TABLE_TYPE
     *
     * @mbg.generated
     */
    public void setTableType(String tableType) {
        this.tableType = tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.STORAGE_TYPE
     *
     * @return the value of TABLES.STORAGE_TYPE
     *
     * @mbg.generated
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.STORAGE_TYPE
     *
     * @param storageType the value for TABLES.STORAGE_TYPE
     *
     * @mbg.generated
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.SQL
     *
     * @return the value of TABLES.SQL
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.SQL
     *
     * @param sql the value for TABLES.SQL
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.REMARKS
     *
     * @return the value of TABLES.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.REMARKS
     *
     * @param remarks the value for TABLES.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.LAST_MODIFICATION
     *
     * @return the value of TABLES.LAST_MODIFICATION
     *
     * @mbg.generated
     */
    public Long getLastModification() {
        return lastModification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.LAST_MODIFICATION
     *
     * @param lastModification the value for TABLES.LAST_MODIFICATION
     *
     * @mbg.generated
     */
    public void setLastModification(Long lastModification) {
        this.lastModification = lastModification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.ID
     *
     * @return the value of TABLES.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.ID
     *
     * @param id the value for TABLES.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TYPE_NAME
     *
     * @return the value of TABLES.TYPE_NAME
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TYPE_NAME
     *
     * @param typeName the value for TABLES.TYPE_NAME
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.TABLE_CLASS
     *
     * @return the value of TABLES.TABLE_CLASS
     *
     * @mbg.generated
     */
    public String getTableClass() {
        return tableClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.TABLE_CLASS
     *
     * @param tableClass the value for TABLES.TABLE_CLASS
     *
     * @mbg.generated
     */
    public void setTableClass(String tableClass) {
        this.tableClass = tableClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLES.ROW_COUNT_ESTIMATE
     *
     * @return the value of TABLES.ROW_COUNT_ESTIMATE
     *
     * @mbg.generated
     */
    public Long getRowCountEstimate() {
        return rowCountEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLES.ROW_COUNT_ESTIMATE
     *
     * @param rowCountEstimate the value for TABLES.ROW_COUNT_ESTIMATE
     *
     * @mbg.generated
     */
    public void setRowCountEstimate(Long rowCountEstimate) {
        this.rowCountEstimate = rowCountEstimate;
    }
}