package org.rhpj.domain.entity;

public class Views {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.VIEW_DEFINITION
     *
     * @mbg.generated
     */
    private String viewDefinition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.CHECK_OPTION
     *
     * @mbg.generated
     */
    private String checkOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.IS_UPDATABLE
     *
     * @mbg.generated
     */
    private String isUpdatable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.TABLE_CATALOG
     *
     * @return the value of VIEWS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.TABLE_CATALOG
     *
     * @param tableCatalog the value for VIEWS.TABLE_CATALOG
     *
     * @mbg.generated
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.TABLE_SCHEMA
     *
     * @return the value of VIEWS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.TABLE_SCHEMA
     *
     * @param tableSchema the value for VIEWS.TABLE_SCHEMA
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.TABLE_NAME
     *
     * @return the value of VIEWS.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.TABLE_NAME
     *
     * @param tableName the value for VIEWS.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.VIEW_DEFINITION
     *
     * @return the value of VIEWS.VIEW_DEFINITION
     *
     * @mbg.generated
     */
    public String getViewDefinition() {
        return viewDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.VIEW_DEFINITION
     *
     * @param viewDefinition the value for VIEWS.VIEW_DEFINITION
     *
     * @mbg.generated
     */
    public void setViewDefinition(String viewDefinition) {
        this.viewDefinition = viewDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.CHECK_OPTION
     *
     * @return the value of VIEWS.CHECK_OPTION
     *
     * @mbg.generated
     */
    public String getCheckOption() {
        return checkOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.CHECK_OPTION
     *
     * @param checkOption the value for VIEWS.CHECK_OPTION
     *
     * @mbg.generated
     */
    public void setCheckOption(String checkOption) {
        this.checkOption = checkOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.IS_UPDATABLE
     *
     * @return the value of VIEWS.IS_UPDATABLE
     *
     * @mbg.generated
     */
    public String getIsUpdatable() {
        return isUpdatable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.IS_UPDATABLE
     *
     * @param isUpdatable the value for VIEWS.IS_UPDATABLE
     *
     * @mbg.generated
     */
    public void setIsUpdatable(String isUpdatable) {
        this.isUpdatable = isUpdatable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.STATUS
     *
     * @return the value of VIEWS.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.STATUS
     *
     * @param status the value for VIEWS.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.REMARKS
     *
     * @return the value of VIEWS.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.REMARKS
     *
     * @param remarks the value for VIEWS.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWS.ID
     *
     * @return the value of VIEWS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWS.ID
     *
     * @param id the value for VIEWS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}